export const categories=[
    {
        id:1,
        name:"Chicken",
        urlParamName:"chicken"
    },
    {
        id:2,
        name:"Soft Drink",
        urlParamName:"softdrink"
    },
    {
        id:3,
        name:"Fruits",
        urlParamName:"fruits"
    },
    {
        id:4,
        name:"Rice",
        urlParamName:"rice"
    },
    {
        id:5,
        name:"Fish",
        urlParamName:"fish"
    },
    {
        id:6,
        name:"Roti",
        urlParamName:"roti"
    },
    {
        id:7,
        name:"Paneer",
        urlParamName:"paneer"
    }
]